"""Aggregate a run directory into report.md (+ optional self-contained HTML)."""

from __future__ import annotations

import json
from pathlib import Path

from . import compose
from .config import LabConfig


def render(cfg: LabConfig, run_dir: Path, html: bool = False) -> Path:
    data = _collect(cfg, run_dir)
    (run_dir / "report.md").write_text(_markdown(data))
    if html:
        (run_dir / "report.html").write_text(_html(data))
    return run_dir / "report.md"


def mask(pw: str) -> str:
    """Mask a placeholder credential for the report (never print full secrets)."""
    if not pw:
        return "-"
    if len(pw) <= 4:
        return "*" * len(pw)
    return pw[:2] + "*" * (len(pw) - 4) + pw[-2:]


# --------------------------------------------------------------------------
def _collect(cfg: LabConfig, run_dir: Path) -> dict:
    meta = _read(run_dir / "meta.json")
    levels = _read(run_dir / "levels.json")
    seeds = _read(run_dir / "seeds.json")
    brute = {}
    for f in sorted(run_dir.glob("*-brute.json")):
        brute[f.stem[: -len("-brute")]] = _read(f)

    try:
        statuses = compose.ps()
    except Exception:
        statuses = {}
    status_rows = []
    for name, t in cfg.targets.items():
        info = statuses.get(name, {})
        status_rows.append({
            "name": name,
            "port": t.port,
            "health": info.get("health") or info.get("state") or "unknown",
            "reachable": compose.reachable(t.host, t.port),
        })

    return {
        "meta": meta,
        "levels": levels,
        "seeds": seeds,
        "brute": brute,
        "status_rows": status_rows,
        "configured_levels": {n: t.security_level for n, t in cfg.targets.items()},
        "run_dir": run_dir,
    }


# --------------------------------------------------------------------------
def _markdown(d: dict) -> str:
    L: list = []
    L.append("# Lab-in-a-Box — Run Report")
    L.append("")
    L.append(f"**Run:** `{d['run_dir'].name}`")
    L.append(f"**Created:** {d['meta'].get('created', '?')}")
    L.append(f"**Network:** {d['meta'].get('network', 'labnet')}")
    L.append("")
    L.append("> Authorized-use-only lab. Never point these tools at systems you do not own.")
    L.append("")

    L.append("## Targets")
    L.append("| Target | Port | Docker | Reachable |")
    L.append("|---|---|---|---|")
    for r in d["status_rows"]:
        L.append(f"| {r['name']} | {r['port']} | {r['health']} | {'yes' if r['reachable'] else 'no'} |")
    L.append("")

    L.append("## Security levels")
    L.append("| Target | Configured | Applied | Applied at |")
    L.append("|---|---|---|---|")
    for name in sorted(d["configured_levels"]):
        configured = d["configured_levels"][name] or "-"
        applied = d["levels"].get(name, {})
        L.append(f"| {name} | {configured} | {applied.get('level', '-')} | {applied.get('at', '-')} |")
    L.append("")

    L.append("## Seeded accounts")
    L.append("| Target | Username | Status | Detail |")
    L.append("|---|---|---|---|")
    if d["seeds"]:
        for name, r in d["seeds"].items():
            L.append(f"| {name} | {r.get('user', '-')} | {r.get('status', '?')} | {r.get('detail', '')} |")
    else:
        L.append("| _none — `labctl seed` not run yet_ | | | |")
    L.append("")
    L.append("> Seeded passwords are intentionally obvious placeholders defined in `lab.yaml` / `.env`.")
    L.append("")

    L.append("## Brute-force runs")
    if d["brute"]:
        for target, res in d["brute"].items():
            L.append(f"### {target}")
            L.append("| Field | Value |")
            L.append("|---|---|")
            L.append(f"| Wordlist | `{res.get('wordlist')}` |")
            L.append(f"| Attempts | {res.get('attempts')} |")
            L.append(f"| Mock run | {'yes' if res.get('mock') else 'no'} |")
            L.append(f"| Started | {res.get('started')} |")
            L.append(f"| Ended | {res.get('ended')} |")
            successes = res.get("successes") or []
            if successes:
                creds = ", ".join(f"`{s['username']}:{mask(s['password'])}`" for s in successes)
                L.append(f"| Successful logins | {creds} |")
            else:
                L.append("| Successful logins | none |")
            if res.get("note"):
                L.append(f"| Note | {res['note']} |")
            L.append("")
    else:
        L.append("_none — run `labctl run-brute --target <name>` first._")
        L.append("")

    L.append("---")
    L.append(f"_Generated by labctl {__import__('labctl').__version__}_")
    return "\n".join(L)


# --------------------------------------------------------------------------
def _html(d: dict) -> str:
    status_rows = "".join(
        f"<tr><td>{r['name']}</td><td>{r['port']}</td><td>{r['health']}</td>"
        f"<td>{'yes' if r['reachable'] else 'no'}</td></tr>"
        for r in d["status_rows"]
    )
    level_rows = "".join(
        f"<tr><td>{name}</td><td>{d['configured_levels'][name] or '-'}</td>"
        f"<td>{d['levels'].get(name, {}).get('level', '-')}</td>"
        f"<td>{d['levels'].get(name, {}).get('at', '-')}</td></tr>"
        for name in sorted(d["configured_levels"])
    )
    seed_rows = "".join(
        f"<tr><td>{name}</td><td>{r.get('user', '-')}</td><td>{r.get('status', '?')}</td>"
        f"<td>{r.get('detail', '')}</td></tr>"
        for name, r in d["seeds"].items()
    ) or "<tr><td colspan=4>none — run <code>labctl seed</code></td></tr>"

    brute_sections = ""
    for target, res in d["brute"].items():
        successes = res.get("successes") or []
        if successes:
            creds = ", ".join(f"<code>{s['username']}:{mask(s['password'])}</code>" for s in successes)
        else:
            creds = "none"
        brute_sections += f"""
        <h3>{target}</h3>
        <table>
          <tr><td>Wordlist</td><td><code>{res.get('wordlist')}</code></td></tr>
          <tr><td>Attempts</td><td>{res.get('attempts')}</td></tr>
          <tr><td>Mock run</td><td>{'yes' if res.get('mock') else 'no'}</td></tr>
          <tr><td>Started</td><td>{res.get('started')}</td></tr>
          <tr><td>Ended</td><td>{res.get('ended')}</td></tr>
          <tr><td>Successful logins</td><td>{creds}</td></tr>
        </table>"""
    if not d["brute"]:
        brute_sections = "<p>none — run <code>labctl run-brute --target &lt;name&gt;</code> first.</p>"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Lab-in-a-Box — run {d['run_dir'].name}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2rem auto; max-width: 64rem; color: #1a1a1a; line-height: 1.5; }}
  h1 {{ border-bottom: 2px solid #ddd; padding-bottom: .4rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: .5rem 0 1.5rem; }}
  th, td {{ border: 1px solid #ddd; padding: .4rem .6rem; text-align: left; font-size: .95rem; }}
  th {{ background: #f4f4f4; }}
  code {{ background: #f4f4f4; padding: .1rem .3rem; border-radius: 3px; }}
  .disclaimer {{ border: 1px solid #e0c060; background: #fff8e0; padding: .6rem .8rem; border-radius: 6px; }}
</style>
</head>
<body>
<h1>Lab-in-a-Box — Run Report</h1>
<p><strong>Run:</strong> <code>{d['run_dir'].name}</code> ·
   <strong>Created:</strong> {d['meta'].get('created', '?')} ·
   <strong>Network:</strong> {d['meta'].get('network', 'labnet')}</p>
<p class="disclaimer"><strong>Authorized-use-only lab.</strong> Never point these tools at systems you do not own.</p>

<h2>Targets</h2>
<table><tr><th>Target</th><th>Port</th><th>Docker</th><th>Reachable</th></tr>{status_rows}</table>

<h2>Security levels</h2>
<table><tr><th>Target</th><th>Configured</th><th>Applied</th><th>Applied at</th></tr>{level_rows}</table>

<h2>Seeded accounts</h2>
<table><tr><th>Target</th><th>Username</th><th>Status</th><th>Detail</th></tr>{seed_rows}</table>

<h2>Brute-force runs</h2>
{brute_sections}

<hr>
<p><small>Generated by labctl</small></p>
</body>
</html>
"""


def _read(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return {}
